---
# tasks file for nginx
- name: install nginx
  apt  : name={{ item }} update_cache=yes force=yes state=present
  with_items :
        - nginx
- name: Creates directory
  file: path=/var/www/wordpress state=directory

- name: copy template of nginx
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx
