---
- hosts: all
  sudo: yes
  tasks:
      - name: Install packages 
        apt: pkg={{item}}  state=installed
        with_items:
              - git-core
              - vim
              - nano
              - whois
      - name: add user
        user: name=student-1 password={{"IjP8sVl4VycNg"}} groups="sudo"
        sudo: true 
      - name: send public key
        copy: src=../mykey dest=/home/root/ owner=root group=root


